### PR TITLE
array of CloudLayers should be empty for clear sky (NSC|NCD|CLR|SKC).

### PR DESCRIPTION
**Pull request by r3wald**
Hi there,

I needed to know when there are no clouds. I think in this case getClouds() should return an empty array.

### CODE REVIEW

**Comment by inouire** [comment]
Hello @r3wald, thank you for contribution.
What do you think of extending this behaviour to the CAVOK case ?

**Comment by r3wald** [comment]
I don't think that would be right: CAVOK means no _relevant_ clouds. That is not the same.

**Comment by r3wald** [comment]
Sorry, I was wrong: the meaning of CAVOK changed. If you take C for "ceiling" then you only have to watch for relevant clouds (5/8, BKN or more).
Nowadays CAVOK stands for "clouds and visibility ok". So you are right, no clouds = empty array.

**Comment by inouire** [comment]
Ok thanks. I'm adding this behaviour, fixing the test and merging it into master

**Comment by r3wald** [comment]
Too bad. I implemented the changes for CAVOK and saw your commit too late (489388dd).

What do you think of an extra CavokChunkDecoder which removes VisibilityCD and CloudCD from the queue is neccessary?

**Comment by inouire** [comment]
Sorry for that. I commited initially to fix the tests, and finished the work.
I'm not sure to understand the purpose of your proposal. Can you please elaborrate ?

**Comment by r3wald** [comment]
At the moment VisibilityChunkDecoder checks for CAVOK. I think it would be better to have an extra Decoder, which 
1. when CAVOK is missing does nothing,
2. when CAVOK occurs sets "maximum visibility", "no clouds" and removes CloudChunkDecoder and VisibilityChunkDecoder from the queue of Decoders.

Your first question was wether to return an empty array for CAVOK. That would be the same question for visibility. I think it's better to return null for invalid or no information at all. For CAVOK it should be something else, may be 9999 or PHP_INT_MAX?

**Comment by inouire** [comment]
@r3wald OK I get it now, thank you for the explanation.
I'm not very comfortable with the fact to modify the Decoder chain on the fly, and I'm pretty happy with the way the chunks have been splitted.

But changing the default value for visibility when CAVOK is another question, I'll submit it to the team here and let you know

**Pull request merged**
